/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cesar.javaarduinorobotica;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.Duration;
import java.time.Instant;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author cesar
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    Arduino arduino = null;
    LinkedList<Comando> gravacao = new LinkedList<Comando>();
    private long delayAcumuladoBase = 0;
    private long delayAcumuladoDistancia = 0;
    private long delayAcumuladoGarra = 0;
    private long delayAcumuladoAltura = 0;

    public MainForm() {
        initComponents();
        listaComando.setModel(new DefaultListModel<>());
        arduino = new Arduino();
        try {
            abrir();
        } catch (InterruptedException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        posicaoBase = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        posicaoGarra = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        posicaoLink2 = new javax.swing.JSlider();
        jPanel4 = new javax.swing.JPanel();
        posicaoLink1 = new javax.swing.JSlider();
        reproduzir = new javax.swing.JButton();
        repetir = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaComando = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Base"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        posicaoBase.setMajorTickSpacing(10);
        posicaoBase.setMaximum(180);
        posicaoBase.setPaintTicks(true);
        posicaoBase.setValue(90);
        posicaoBase.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                posicaoBaseStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(posicaoBase, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Garra"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        posicaoGarra.setMajorTickSpacing(10);
        posicaoGarra.setMaximum(180);
        posicaoGarra.setPaintTicks(true);
        posicaoGarra.setValue(90);
        posicaoGarra.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                posicaoGarraStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(posicaoGarra, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Link 2"));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        posicaoLink2.setMajorTickSpacing(10);
        posicaoLink2.setMaximum(180);
        posicaoLink2.setPaintTicks(true);
        posicaoLink2.setToolTipText("");
        posicaoLink2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                posicaoLink2StateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(posicaoLink2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Link 1"));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        posicaoLink1.setMajorTickSpacing(10);
        posicaoLink1.setMaximum(180);
        posicaoLink1.setPaintTicks(true);
        posicaoLink1.setValue(90);
        posicaoLink1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                posicaoLink1StateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(posicaoLink1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel4, gridBagConstraints);

        reproduzir.setText("Reproduzir Tudo");
        reproduzir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproduzirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(reproduzir, gridBagConstraints);

        repetir.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(repetir, gridBagConstraints);

        listaComando.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaComandoMouseClicked(evt);
            }
        });
        listaComando.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                listaComandoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(listaComando);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        getContentPane().add(jSeparator1, gridBagConstraints);

        jButton9.setText("Gravar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jButton9, gridBagConstraints);

        jButton10.setText("Posição Inicial");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jButton10, gridBagConstraints);

        jButton11.setText("Reproduzir Selecionados");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jButton11, gridBagConstraints);

        setSize(new java.awt.Dimension(883, 266));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reproduzirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproduzirActionPerformed
        if (gravacao.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Não existe gravação para reproduzir!");
        } else {
            try {
                reproduzir(gravacao.toArray());
            } catch (InterruptedException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao reproduzir:\n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_reproduzirActionPerformed

    private void listaComandoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaComandoMouseClicked
        if (evt.getClickCount() == 2) {
            editarComando();
        }
    }//GEN-LAST:event_listaComandoMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        gravarComando();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void listaComandoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaComandoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            removerComando();
        }
    }//GEN-LAST:event_listaComandoKeyReleased

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            resetPosicao();
        } catch (InterruptedException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (gravacao.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Não existe gravação para reproduzir!");
        } else {
            try {
                reproduzir(listaComando.getSelectedValues());
            } catch (InterruptedException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao reproduzir:\n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void posicaoLink2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_posicaoLink2StateChanged
        delayAcumuladoAltura += enviaComando(ServoEnum.ALTURA.getIdentificador(), (int) posicaoLink2.getValue());
    }//GEN-LAST:event_posicaoLink2StateChanged

    private void posicaoLink1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_posicaoLink1StateChanged
        delayAcumuladoDistancia += enviaComando(ServoEnum.DISTANCIA.getIdentificador(), (int) posicaoLink1.getValue());
    }//GEN-LAST:event_posicaoLink1StateChanged

    private void posicaoBaseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_posicaoBaseStateChanged
        delayAcumuladoBase += enviaComando(ServoEnum.BASE.getIdentificador(), (int) posicaoBase.getValue());
    }//GEN-LAST:event_posicaoBaseStateChanged

    private void posicaoGarraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_posicaoGarraStateChanged
        delayAcumuladoGarra += enviaComando(ServoEnum.GARRA.getIdentificador(), (int) posicaoGarra.getValue());
    }//GEN-LAST:event_posicaoGarraStateChanged

    private long enviaComando(String identificador, int posicao) {
        Instant before = Instant.now();
        String comando = identificador + (String.format("%02d", posicao));
        long delta = 10;
        arduino.comunicacaoArduino(comando);
        Instant after = Instant.now();
        delta += Duration.between(before, after).toMillis();
        return delta;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".contains(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> listaComando;
    private javax.swing.JSlider posicaoBase;
    private javax.swing.JSlider posicaoGarra;
    private javax.swing.JSlider posicaoLink1;
    private javax.swing.JSlider posicaoLink2;
    private javax.swing.JSpinner repetir;
    private javax.swing.JButton reproduzir;
    // End of variables declaration//GEN-END:variables

    private void gravarComando() {

        if (delayAcumuladoBase > 0) {
            gravaComando(ServoEnum.BASE.getIdentificador(), (int) posicaoBase.getValue(), delayAcumuladoBase);
            delayAcumuladoBase = 0;
        }

        if (delayAcumuladoDistancia > 0) {
            gravaComando(ServoEnum.DISTANCIA.getIdentificador(), (int) posicaoLink1.getValue(), delayAcumuladoDistancia);
            delayAcumuladoDistancia = 0;
        }

        if (delayAcumuladoGarra > 0) {
            gravaComando(ServoEnum.GARRA.getIdentificador(), (int) posicaoGarra.getValue(), delayAcumuladoGarra);
            delayAcumuladoGarra = 0;
        }

        if (delayAcumuladoAltura > 0) {
            gravaComando(ServoEnum.ALTURA.getIdentificador(), (int) posicaoLink2.getValue(), delayAcumuladoAltura);
            delayAcumuladoAltura = 0;
        }

        salvar();
    }

    private void resetPosicao() throws InterruptedException {
        enviaComando(ServoEnum.ALTURA.getIdentificador(), 90);
        enviaComando(ServoEnum.BASE.getIdentificador(), 90);
        enviaComando(ServoEnum.DISTANCIA.getIdentificador(), 90);
        enviaComando(ServoEnum.GARRA.getIdentificador(), 90);
        posicaoLink2.setValue(90);
        posicaoBase.setValue(90);
        posicaoLink1.setValue(90);
        posicaoGarra.setValue(90);

        delayAcumuladoBase = 0;
        delayAcumuladoDistancia = 0;
        delayAcumuladoGarra = 0;
        delayAcumuladoAltura = 0;
        Thread.sleep(200);
    }

    private void reproduzir(Object[] comandos) throws InterruptedException {
        resetPosicao();
        int qtde = Integer.parseInt(repetir.getValue().toString());
        Thread worker = new Thread() {
            public void run() {
                for (int i = 0; i < qtde; i++) {
                    for (Object obj : comandos) {
                        Comando comando = (Comando) obj;
                        if (comando.getIdentificadorServo().equals(ServoEnum.ALTURA.getIdentificador())) {
                            posicaoLink2.getModel().setValue(comando.getPosicao());
                        } else if (comando.getIdentificadorServo().equals(ServoEnum.BASE.getIdentificador())) {
                            posicaoBase.getModel().setValue(comando.getPosicao());
                        } else if (comando.getIdentificadorServo().equals(ServoEnum.DISTANCIA.getIdentificador())) {
                            posicaoLink1.getModel().setValue(comando.getPosicao());
                        } else if (comando.getIdentificadorServo().equals(ServoEnum.GARRA.getIdentificador())) {
                            posicaoGarra.getModel().setValue(comando.getPosicao());
                        }

                        try {
                            Thread.sleep(comando.getDelay());
                        } catch (InterruptedException ex) {
                            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        };
        worker.start();
    }

    private void salvar() {
        try {
            FileOutputStream fileOut = new FileOutputStream("gravacao");
            ObjectOutputStream out = new ObjectOutputStream(fileOut);
            out.writeObject(gravacao);
            out.close();
            fileOut.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar arquivo de gravação:\n" + e.getMessage());
        }
    }

    private void abrir() throws InterruptedException {
        resetPosicao();
        try {
            if (new File("gravacao").exists()) {
                FileInputStream fileIn = new FileInputStream("gravacao");
                ObjectInputStream in = new ObjectInputStream(fileIn);
                gravacao = (LinkedList<Comando>) in.readObject();
                in.close();
                fileIn.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao abrir arquivo de gravação:\n" + e.getMessage());
        }

        carregarListaComando();
    }

    private void carregarListaComando() {
        DefaultListModel model = (DefaultListModel) listaComando.getModel();
        model.removeAllElements();
        for (Comando comando : gravacao) {
            model.addElement(comando);
        }

    }

    private void gravaComando(String identificador, int posicao, long delay) {
        Comando novoComando = new Comando(identificador, posicao, (int) delay);
        gravacao.add(novoComando);
        carregarListaComando();

    }

    private void removerComando() {
        if (listaComando.getSelectedIndex() > -1) {

            int reply = JOptionPane.showConfirmDialog(rootPane, "Deseja remover o comando selecionado?", "Confirma", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                gravacao.removeAll(listaComando.getSelectedValuesList());
                salvar();
                carregarListaComando();
            }

        }
    }

    private void editarComando() {
        Comando comando = (Comando) ((DefaultListModel) listaComando.getModel()).getElementAt(listaComando.getSelectedIndex());
        new EditarComando(this, rootPaneCheckingEnabled, comando).setVisible(true);
        salvar();
        carregarListaComando();
    }
}
