/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cesar.javaarduinorobotica;

import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JSlider;
import javax.swing.JSpinner;

/**
 *
 * @author cesar
 */
public class TelaPrincipal extends javax.swing.JFrame {

    TelaPrincipalControle controle;

    /**
     * Creates new form TelaPrincipal
     */

    public TelaPrincipal() throws Exception {
        initComponents();
        controle = new TelaPrincipalControle(this);

        listaComando.setModel(new DefaultListModel<>());

        posicaoLink1.setInverted(true);
        posicaoLink2.setInverted(true);
        try {
            controle.abrir();
        } catch (InterruptedException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        posicaoBase = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        posicaoGarra = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        posicaoLink2 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        posicaoPunho = new javax.swing.JSlider();
        reproduzir = new javax.swing.JButton();
        repetir = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaComando = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        botaoGravar = new javax.swing.JButton();
        posicaoInicial = new javax.swing.JButton();
        reproduzirSelecionados = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        posicaoLink1 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Base", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        posicaoBase.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        posicaoBase.setMajorTickSpacing(10);
        posicaoBase.setMaximum(180);
        posicaoBase.setPaintTicks(true);
        posicaoBase.setValue(90);
        posicaoBase.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                posicaoBaseStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(posicaoBase, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Garra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        jPanel2.setLayout(new java.awt.GridBagLayout());

        posicaoGarra.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        posicaoGarra.setMajorTickSpacing(10);
        posicaoGarra.setMaximum(180);
        posicaoGarra.setPaintTicks(true);
        posicaoGarra.setValue(90);
        posicaoGarra.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                posicaoGarraStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(posicaoGarra, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Fechar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Abrir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel2.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Link 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        jPanel3.setLayout(new java.awt.GridBagLayout());

        posicaoLink2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        posicaoLink2.setMajorTickSpacing(10);
        posicaoLink2.setMaximum(180);
        posicaoLink2.setPaintTicks(true);
        posicaoLink2.setToolTipText("");
        posicaoLink2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                posicaoLink2StateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(posicaoLink2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Avança");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Recua");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel3.add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "punho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        jPanel4.setLayout(new java.awt.GridBagLayout());

        posicaoPunho.setMajorTickSpacing(10);
        posicaoPunho.setMaximum(180);
        posicaoPunho.setOrientation(javax.swing.JSlider.VERTICAL);
        posicaoPunho.setPaintTicks(true);
        posicaoPunho.setValue(90);
        posicaoPunho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                posicaoPunhoStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(posicaoPunho, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel4, gridBagConstraints);

        reproduzir.setText("Reproduzir Tudo");
        reproduzir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproduzirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(reproduzir, gridBagConstraints);

        repetir.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(repetir, gridBagConstraints);

        listaComando.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaComandoMouseClicked(evt);
            }
        });
        listaComando.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                listaComandoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(listaComando);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        getContentPane().add(jSeparator1, gridBagConstraints);

        botaoGravar.setText("Gravar");
        botaoGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGravarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(botaoGravar, gridBagConstraints);

        posicaoInicial.setText("Posição Inicial");
        posicaoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoInicialActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(posicaoInicial, gridBagConstraints);

        reproduzirSelecionados.setText("Reproduzir Selecionados");
        reproduzirSelecionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproduzirSelecionadosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        getContentPane().add(reproduzirSelecionados, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Link 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        jPanel5.setLayout(new java.awt.GridBagLayout());

        posicaoLink1.setMajorTickSpacing(10);
        posicaoLink1.setMaximum(180);
        posicaoLink1.setOrientation(javax.swing.JSlider.VERTICAL);
        posicaoLink1.setPaintTicks(true);
        posicaoLink1.setValue(90);
        posicaoLink1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                posicaoLink1StateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel5.add(posicaoLink1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel5, gridBagConstraints);

        setSize(new java.awt.Dimension(763, 458));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reproduzirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproduzirActionPerformed
        if (controle.gravacao.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Não existe gravação para reproduzir!");
        } else {
            try {
                controle.reproduzir(controle.gravacao.toArray());
            } catch (InterruptedException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao reproduzir:\n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_reproduzirActionPerformed

    private void listaComandoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaComandoMouseClicked
        if (evt.getClickCount() == 2) {
            controle.editarComando();
        }
    }//GEN-LAST:event_listaComandoMouseClicked

    private void botaoGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGravarActionPerformed
        controle.gravarComando();
    }//GEN-LAST:event_botaoGravarActionPerformed

    private void listaComandoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaComandoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            controle.removerComando();
        }
    }//GEN-LAST:event_listaComandoKeyReleased

    private void posicaoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoInicialActionPerformed
        try {
            controle.posicaoInicial();
        } catch (InterruptedException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_posicaoInicialActionPerformed

    private void reproduzirSelecionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproduzirSelecionadosActionPerformed
        if (controle.gravacao.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Não existe gravação para reproduzir!");
        } else {
            try {
                controle.reproduzir(listaComando.getSelectedValues());
            } catch (InterruptedException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao reproduzir:\n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_reproduzirSelecionadosActionPerformed

    private void posicaoLink2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_posicaoLink2StateChanged
        controle.enviaComando(ServoEnum.ALTURA.getIdentificador(), (int) posicaoLink2.getValue());
    }//GEN-LAST:event_posicaoLink2StateChanged

    private void posicaoPunhoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_posicaoPunhoStateChanged
        controle.enviaComando(ServoEnum.PUNHO.getIdentificador(), (int) posicaoPunho.getValue());
    }//GEN-LAST:event_posicaoPunhoStateChanged

    private void posicaoBaseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_posicaoBaseStateChanged
        controle.enviaComando(ServoEnum.BASE.getIdentificador(), (int) posicaoBase.getValue());
    }//GEN-LAST:event_posicaoBaseStateChanged

    private void posicaoGarraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_posicaoGarraStateChanged
        controle.enviaComando(ServoEnum.GARRA.getIdentificador(), (int) posicaoGarra.getValue());
    }//GEN-LAST:event_posicaoGarraStateChanged

    private void posicaoLink1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_posicaoLink1StateChanged
        controle.enviaComando(ServoEnum.DISTANCIA.getIdentificador(), (int) posicaoLink1.getValue());
    }//GEN-LAST:event_posicaoLink1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".contains(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    new TelaPrincipal().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    public TelaPrincipalControle getControle() {
        return controle;
    }

    public JButton getjButton10() {
        return posicaoInicial;
    }

    public JButton getjButton11() {
        return reproduzirSelecionados;
    }

    public JButton getjButton9() {
        return botaoGravar;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public JPanel getjPanel5() {
        return jPanel5;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public JList<String> getListaComando() {
        return listaComando;
    }

    public JSlider getPosicaoBase() {
        return posicaoBase;
    }

    public JSlider getPosicaoGarra() {
        return posicaoGarra;
    }

    public JSlider getPosicaoLink1() {
        return posicaoLink1;
    }

    public JSlider getPosicaoLink2() {
        return posicaoLink2;
    }

    public JSlider getPosicaoPunho() {
        return posicaoPunho;
    }

    public JSpinner getRepetir() {
        return repetir;
    }

    public JButton getReproduzir() {
        return reproduzir;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoGravar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> listaComando;
    private javax.swing.JSlider posicaoBase;
    private javax.swing.JSlider posicaoGarra;
    private javax.swing.JButton posicaoInicial;
    private javax.swing.JSlider posicaoLink1;
    private javax.swing.JSlider posicaoLink2;
    private javax.swing.JSlider posicaoPunho;
    private javax.swing.JSpinner repetir;
    private javax.swing.JButton reproduzir;
    private javax.swing.JButton reproduzirSelecionados;
    // End of variables declaration//GEN-END:variables

}
